import type { Metadata } from "next";
import { Noto_Sans_Display } from "next/font/google";
import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    SignInButton,
    UserButton,
  } from '@clerk/nextjs';

import "./globals.css";

const noto = Noto_Sans_Display ({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"]
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="pt-br">
                <body className={noto.className}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
